# Generated by Django 5.2.1 on 2025-05-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='cashed_out_at',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
