# Generated by Django 5.2.1 on 2025-05-17 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_bet_cashed_out_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameround',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='start_time',
        ),
        migrations.AddField(
            model_name='gameround',
            name='client_seed',
            field=models.CharField(default='default-seed', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameround',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gameround',
            name='server_seed',
            field=models.CharField(default='default-server-seed', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameround',
            name='crash_point',
            field=models.FloatField(default=1.01),
            preserve_default=False,
        ),
    ]
