# Generated by Django 5.2.1 on 2025-05-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_gameround_end_time_remove_gameround_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='cashout_multiplier',
            new_name='cash_out_multiplier',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='cashed_out',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='placed_at',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='user',
        ),
        migrations.AddField(
            model_name='bet',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
